# 04 - Kampanye tuning hyperparameter

Menjalankan grid yang dirancang di `tuning_grids/`. Prinsipnya human-in-the-loop:
tidak ada pencarian otomatis, urutan konfigurasi ditentukan manusia, dan setiap
baris hasil membawa kolom `catatan` yang merekam alasan konfigurasi itu dicoba.

Seleksi memakai split validation. Split test tidak disentuh sama sekali di
notebook ini.

Metode: grid kombinatorial untuk sumbu yang saling terkait, coordinate descent
untuk sumbu yang independen. Untuk RM-a, `lr`, `epochs`, dan `batch` bersama-sama
menentukan lintasan optimasi (batch 32 pada 5 epoch memberi separuh jumlah
langkah pembaruan dibanding batch 16), sehingga ketiganya harus digrid bersama;
`warmup_ratio` dan `weight_decay` efektif independen sehingga cukup dicoba satu
per satu di sel pemenang.

Prasyarat: `02_preprocessing.ipynb` sudah dijalankan.

In [1]:
import pandas as pd

from src.config import settings
from src.services.campaign import CampaignRunner

OUT_DIR = settings.default_out_dir

runner = CampaignRunner(out_dir=OUT_DIR)
runner.write_hardware()
print("device   :", runner.device)
print("keluaran :", runner.out_dir)

/workspace/indobert-with-rac/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

2026-09-14 16:50:56,541 | INFO     | src.services.data | Data dimuat: train=6588 val=1402 test=1405 | device=cuda | encoder=indobenchmark/indobert-base-p2

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

device   : cuda
keluaran : /workspace/indobert-with-rac/outputs/tuning

## 1. Kalibrasi biaya

Jalankan satu konfigurasi RM-a lebih dulu untuk mengukur waktu dan memori
sesungguhnya di mesin ini, sebelum mempertaruhkan berjam-jam pada grid penuh.
Kalau memori kurang, turunkan `MICRO_BATCH` di `.env`; batch efektif tidak
berubah karena selisihnya ditutup akumulasi gradien.

In [2]:
kalibrasi = runner.run(
    "rma",
    {"lr": 2e-5, "epochs": 5, "batch": 16, "warmup_ratio": 0.1, "weight_decay": 0.01},
    note="kalibrasi biaya: baseline kanonik, sekaligus run #1 grid",
)

per_run = kalibrasi["train_time_s"]
print(f"satu run RM-a: {per_run:.0f} s | peak {kalibrasi['peak_mem_mb']:.0f} MB")
print(f"perkiraan 26 run RM-a: {per_run * 26 / 60:.0f} menit")

2026-09-14 16:50:57,638 | INFO     | src.services.campaign | [rma] RUN #1 {'lr': 2e-05, 'epochs': 5, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 8, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 51823.33it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 16:50:58,871 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 16:51:24,359 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9586
2026-09-14 16:51:50,047 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9682
2026-09-14 16:52:16,067 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9762
2026-09-14 16:52:41,696 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9762
2026-09-14 16:53:07,142 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9784
2026-09-14 16:53:07,596 | INFO     | src.services.run_log | Juara baru untuk rma: val F1-macro 0.9784 (sebelumnya -1.0000)
2026-09-14 16:53:09,556 | INFO     | src.services.campaign | [rma] RUN #1 val F1-macro 0.9784 (epoch terbaik 5)
satu run RM-a: 128 s | peak 2334 MB
perkiraan 26 run RM-a: 56 menit

## 2. Muat rancangan grid

In [3]:
GRID_DIR = settings.data_dir.parent / "tuning_grids"

def muat_grid(nama: str) -> list[dict]:
    frame = pd.read_csv(GRID_DIR / nama)
    catatan = frame.pop("catatan") if "catatan" in frame.columns else ""
    return [
        {"config": {k: v for k, v in baris.items() if pd.notna(v)},
         "note": catatan.iloc[i] if hasattr(catatan, "iloc") else ""}
        for i, baris in enumerate(frame.to_dict("records"))
    ]

for berkas in sorted(GRID_DIR.glob("*.csv")):
    print(f"  {berkas.name}: {len(pd.read_csv(berkas))} konfigurasi")

  RMA_TUNING_GRID.csv: 24 konfigurasi
  RMA_TUNING_GRID_STAGE2.csv: 2 konfigurasi
  RMB_TUNING_GRID.csv: 4 konfigurasi
  RMB_TUNING_GRID_STAGE1B.csv: 2 konfigurasi
  RMB_TUNING_GRID_STAGE2.csv: 15 konfigurasi
  RMB_TUNING_GRID_STAGE3.csv: 6 konfigurasi
  RMC_TUNING_GRID.csv: 66 konfigurasi
  RMC_TUNING_GRID_STAGE2.csv: 1 konfigurasi

## Melanjutkan kampanye yang terputus

`run_batch` menyaring konfigurasi yang sudah ada di riwayat secara default
(`resume=True`), sehingga sel batch di bawah aman dijalankan ulang apa adanya
setelah kernel mati, listrik padam, atau proses dihentikan. Yang sudah selesai
dilewati, penomoran run berlanjut, dan `best.json` tetap terjaga.

Yang hilang saat terputus hanyalah run yang sedang berjalan saat itu; run yang
sudah selesai ditulis atomik ke `runs_{skenario}.csv` begitu selesai.

Perbandingan memakai konfigurasi LENGKAP setelah nilai default diisi, dan untuk
RM-a `micro_batch` dinormalkan ke nilai efektifnya (`min(batch, micro_batch)`) —
nilai itulah yang menentukan ukuran batch di `DataLoader`.

Sel di bawah memperlihatkan apa yang tersisa sebelum batch dijalankan.

In [4]:
def sisa(skenario: str, berkas: str) -> None:
    permintaan = muat_grid(berkas)
    tersisa = runner.pending_requests(skenario, permintaan)
    print(f"{berkas:34s} {len(permintaan) - len(tersisa):>3d}/{len(permintaan)} selesai, "
          f"{len(tersisa)} tersisa")

sisa("rma", "RMA_TUNING_GRID.csv")
sisa("rma", "RMA_TUNING_GRID_STAGE2.csv")
for berkas in ("RMB_TUNING_GRID.csv", "RMB_TUNING_GRID_STAGE1B.csv",
               "RMB_TUNING_GRID_STAGE2.csv", "RMB_TUNING_GRID_STAGE3.csv"):
    sisa("rmb", berkas)
for berkas in ("RMC_TUNING_GRID.csv", "RMC_TUNING_GRID_STAGE2.csv"):
    sisa("rmc", berkas)

RMA_TUNING_GRID.csv                  0/24 selesai, 24 tersisa
RMA_TUNING_GRID_STAGE2.csv           0/2 selesai, 2 tersisa
RMB_TUNING_GRID.csv                  0/4 selesai, 4 tersisa
RMB_TUNING_GRID_STAGE1B.csv          0/2 selesai, 2 tersisa
RMB_TUNING_GRID_STAGE2.csv           0/15 selesai, 15 tersisa
RMB_TUNING_GRID_STAGE3.csv           0/6 selesai, 6 tersisa
RMC_TUNING_GRID.csv                  0/66 selesai, 66 tersisa
RMC_TUNING_GRID_STAGE2.csv           0/1 selesai, 1 tersisa

## 3. RM-a

Grid tahap 1 menggarap tiga sumbu yang saling terkait. Konfigurasi yang gagal
diisolasi ke `runs_rma_errors.csv` dan tidak menghentikan sisa antrean.

In [5]:
hasil_rma = runner.run_batch("rma", muat_grid("RMA_TUNING_GRID.csv"),
                             batch_id="rma_tahap1_grid")
hasil_rma.nlargest(10, "val_f1_macro")[
    ["run_id", "lr", "epochs", "batch", "val_f1_macro", "val_f1_judi",
     "train_time_s", "is_tie_with_best"]
]

2026-09-14 16:53:09,595 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 24 konfigurasi akan dijalankan
2026-09-14 16:53:09,595 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 1/24 (perkiraan sisa 0.0 menit)
2026-09-14 16:53:09,597 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 1 run
2026-09-14 16:53:09,597 | INFO     | src.services.campaign | [rma] RUN #2 {'lr': 2e-05, 'epochs': 5, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 54510.61it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 16:53:10,602 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 16:53:31,868 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9584
2026-09-14 16:53:53,340 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9587
2026-09-14 16:54:15,040 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9747
2026-09-14 16:54:57,920 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9749
2026-09-14 16:54:58,283 | INFO     | src.services.campaign | [rma] RUN #2 val F1-macro 0.9749 (epoch terbaik 5)
2026-09-14 16:54:58,284 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 2/24 (perkiraan sisa 41.7 menit)
2026-09-14 16:54:58,287 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 2 run
2026-09-14 16:54:58,287 | INFO     | src.services.campaign | [rma] RUN #3 {'lr': 2e-05, 'epochs': 3, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 22192.67it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 16:54:59,271 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 16:55:20,574 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9595
2026-09-14 16:55:41,987 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9659
2026-09-14 16:56:26,003 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9543
2026-09-14 16:56:47,614 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9215
2026-09-14 16:57:08,884 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9710
2026-09-14 16:57:30,529 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9683
2026-09-14 16:57:51,852 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9751
2026-09-14 16:58:13,371 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9763
2026-09-14 16:58:34,843 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9751
2026-09-14 16:58:56,109 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9740
2026-09-14 16:58:56,260 | INFO     | src.services.campaign | [rma] RUN #4 val F1-macro 0.9763 (epoch terbaik 6)
2026-09-14 16:58:56,265 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 4/24 (perkiraan sisa 40.4 menit)
2026-09-14 16:58:56,268 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 4 run
2026-09-14 16:58:56,269 | INFO     | src.services.campaign | [rma] RUN #5 {'lr': 1e-05, 'epochs': 5, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56255.75it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 16:58:57,225 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 16:59:18,527 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9596
2026-09-14 16:59:40,063 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9678
2026-09-14 17:00:01,551 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9772
2026-09-14 17:00:23,048 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9762
2026-09-14 17:00:44,291 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9785
2026-09-14 17:00:44,603 | INFO     | src.services.run_log | Juara baru untuk rma: val F1-macro 0.9785 (sebelumnya 0.9784)
2026-09-14 17:00:46,461 | INFO     | src.services.campaign | [rma] RUN #5 val F1-macro 0.9785 (epoch terbaik 5)
2026-09-14 17:00:46,462 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 5/24 (perkiraan sisa 38.1 menit)
2026-09-14 17:00:46,465 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 5 run
2026-09-14 17:00:46,465 | INFO     | src.services.campaign | [rma] RUN #6 {'lr': 1e-05, 'epochs': 3, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 58209.53it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:00:47,414 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:01:08,674 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9629
2026-09-14 17:01:30,068 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9612
2026-09-14 17:01:51,307 | INFO     | src.services.training | [RM-a] epoch 3/3 val F1-macro 0.9681
2026-09-14 17:01:51,718 | INFO     | src.services.campaign | [rma] RUN #6 val F1-macro 0.9681 (epoch terbaik 3)
2026-09-14 17:01:51,723 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 6/24 (perkiraan sisa 33.1 menit)
2026-09-14 17:01:51,726 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 6 run
2026-09-14 17:01:51,726 | INFO     | src.services.campaign | [rma] RUN #7 {'lr': 1e-05, 'epochs': 8, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 54793.31it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:01:52,642 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:02:13,932 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9518
2026-09-14 17:02:35,455 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9192
2026-09-14 17:02:56,701 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9760
2026-09-14 17:03:18,247 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9774
2026-09-14 17:03:39,724 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9695
2026-09-14 17:04:00,966 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9660
2026-09-14 17:04:22,238 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9698
2026-09-14 17:04:43,564 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9747
2026-09-14 17:04:43,712 | INFO     | src.services.campaign | [rma] RUN #7 val F1-macro 0.9774 (epoch terbaik 4)
2026-09-14 17:04:43,717 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 7/24 (perkiraan sisa 34.7 menit)
2026-09-14 17:04:43,720 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 7 run
2026-09-14 17:04:43,720 | INFO     | src.services.campaign | [rma] RUN #8 {'lr': 3e-05, 'epochs': 5, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 60303.92it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:04:44,591 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:05:05,923 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9608
2026-09-14 17:05:27,468 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9540
2026-09-14 17:05:48,698 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9717
2026-09-14 17:06:10,172 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9679
2026-09-14 17:06:31,420 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9713
2026-09-14 17:06:31,573 | INFO     | src.services.campaign | [rma] RUN #8 val F1-macro 0.9717 (epoch terbaik 3)
2026-09-14 17:06:31,579 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 8/24 (perkiraan sisa 32.5 menit)
2026-09-14 17:06:31,581 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 8 run
2026-09-14 17:06:31,582 | INFO     | src.services.campaign | [rma] RUN #9 {'lr': 3e-05, 'epochs': 3, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56442.15it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:06:32,609 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:06:53,900 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9628
2026-09-14 17:07:15,398 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9704
2026-09-14 17:07:36,851 | INFO     | src.services.training | [RM-a] epoch 3/3 val F1-macro 0.9688
2026-09-14 17:07:37,006 | INFO     | src.services.campaign | [rma] RUN #9 val F1-macro 0.9704 (epoch terbaik 2)
2026-09-14 17:07:37,011 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 9/24 (perkiraan sisa 28.9 menit)
2026-09-14 17:07:37,014 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 9 run
2026-09-14 17:07:37,015 | INFO     | src.services.campaign | [rma] RUN #10 {'lr': 3e-05, 'epochs': 8, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56907.79it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:07:38,040 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:07:59,227 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9617
2026-09-14 17:08:20,713 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9697
2026-09-14 17:08:42,270 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9619
2026-09-14 17:09:03,508 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9661
2026-09-14 17:09:24,784 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9651
2026-09-14 17:09:46,096 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9674
2026-09-14 17:10:07,403 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9711
2026-09-14 17:10:28,962 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9711
2026-09-14 17:10:29,114 | INFO     | src.services.campaign | [rma] RUN #10 val F1-macro 0.9711 (epoch terbaik 7)
2026-09-14 17:10:29,119 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 10/24 (perkiraan sisa 28.9 menit)
2026-09-14 17:10:29,122 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 10 run
2026-09-14 17:10:29,122 | INFO     | src.services.campaign | [rma] RUN #11 {'lr': 5e-05, 'epochs': 5, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 55009.98it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:10:30,183 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:10:51,431 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9660
2026-09-14 17:11:12,930 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9702
2026-09-14 17:11:34,411 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9590
2026-09-14 17:11:55,629 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9740
2026-09-14 17:12:17,185 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9747
2026-09-14 17:12:17,499 | INFO     | src.services.campaign | [rma] RUN #11 val F1-macro 0.9747 (epoch terbaik 5)
2026-09-14 17:12:17,500 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 11/24 (perkiraan sisa 26.8 menit)
2026-09-14 17:12:17,502 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 11 run
2026-09-14 17:12:17,503 | INFO     | src.services.campaign | [rma] RUN #12 {'lr': 5e-05, 'epochs': 3, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57055.61it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:12:18,513 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:12:39,720 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9317
2026-09-14 17:13:01,166 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9604
2026-09-14 17:13:22,536 | INFO     | src.services.training | [RM-a] epoch 3/3 val F1-macro 0.9670
2026-09-14 17:13:23,011 | INFO     | src.services.campaign | [rma] RUN #12 val F1-macro 0.9670 (epoch terbaik 3)
2026-09-14 17:13:23,013 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 12/24 (perkiraan sisa 23.9 menit)
2026-09-14 17:13:23,015 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 12 run
2026-09-14 17:13:23,016 | INFO     | src.services.campaign | [rma] RUN #13 {'lr': 5e-05, 'epochs': 8, 'batch': 16, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 55378.62it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:13:23,889 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:13:45,100 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9474
2026-09-14 17:14:06,467 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9349
2026-09-14 17:14:27,713 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9762
2026-09-14 17:14:49,171 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9384
2026-09-14 17:15:10,413 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9701
2026-09-14 17:15:31,711 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9701
2026-09-14 17:15:52,930 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9712
2026-09-14 17:16:14,197 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9714
2026-09-14 17:16:14,351 | INFO     | src.services.campaign | [rma] RUN #13 val F1-macro 0.9762 (epoch terbaik 3)
2026-09-14 17:16:14,352 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 13/24 (perkiraan sisa 23.1 menit)
2026-09-14 17:16:14,355 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 13 run
2026-09-14 17:16:14,355 | INFO     | src.services.campaign | [rma] RUN #14 {'lr': 2e-05, 'epochs': 5, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56217.86it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:16:15,259 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:16:31,935 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9697
2026-09-14 17:16:48,562 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9663
2026-09-14 17:17:04,968 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9782
2026-09-14 17:17:21,666 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9822
2026-09-14 17:17:38,268 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9783
2026-09-14 17:17:38,426 | INFO     | src.services.run_log | Juara baru untuk rma: val F1-macro 0.9822 (sebelumnya 0.9785)
2026-09-14 17:17:40,105 | INFO     | src.services.campaign | [rma] RUN #14 val F1-macro 0.9822 (epoch terbaik 4)
2026-09-14 17:17:40,106 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 14/24 (perkiraan sisa 20.7 menit)
2026-09-14 17:17:40,109 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 14 run
2026-09-14 17:17:40,109 | INFO     | src.services.campaign | [rma] RUN #15 {'lr': 2e-05, 'epochs': 3, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57416.70it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:17:40,967 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:17:57,397 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9722
2026-09-14 17:18:13,961 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9661
2026-09-14 17:18:30,377 | INFO     | src.services.training | [RM-a] epoch 3/3 val F1-macro 0.9735
2026-09-14 17:18:30,715 | INFO     | src.services.campaign | [rma] RUN #15 val F1-macro 0.9735 (epoch terbaik 3)
2026-09-14 17:18:30,716 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 15/24 (perkiraan sisa 18.1 menit)
2026-09-14 17:18:30,719 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 15 run
2026-09-14 17:18:30,719 | INFO     | src.services.campaign | [rma] RUN #16 {'lr': 2e-05, 'epochs': 8, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57507.68it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:18:31,545 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:18:47,993 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9712
2026-09-14 17:19:04,508 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9600
2026-09-14 17:19:20,819 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9723
2026-09-14 17:19:37,412 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9705
2026-09-14 17:19:53,738 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9710
2026-09-14 17:20:10,160 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9771
2026-09-14 17:20:26,768 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9684
2026-09-14 17:20:43,190 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9696
2026-09-14 17:20:43,337 | INFO     | src.services.campaign | [rma] RUN #16 val F1-macro 0.9771 (epoch terbaik 6)
2026-09-14 17:20:43,342 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 16/24 (perkiraan sisa 16.5 menit)
2026-09-14 17:20:43,345 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 16 run
2026-09-14 17:20:43,345 | INFO     | src.services.campaign | [rma] RUN #17 {'lr': 1e-05, 'epochs': 5, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 55202.81it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:20:44,266 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:21:00,697 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9602
2026-09-14 17:21:17,360 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9680
2026-09-14 17:21:34,084 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9760
2026-09-14 17:21:50,938 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9750
2026-09-14 17:22:07,396 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9758
2026-09-14 17:22:07,554 | INFO     | src.services.campaign | [rma] RUN #17 val F1-macro 0.9760 (epoch terbaik 3)
2026-09-14 17:22:07,559 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 17/24 (perkiraan sisa 14.5 menit)
2026-09-14 17:22:07,562 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 17 run
2026-09-14 17:22:07,562 | INFO     | src.services.campaign | [rma] RUN #18 {'lr': 1e-05, 'epochs': 3, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56388.76it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:22:08,437 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:22:24,862 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9656
2026-09-14 17:22:41,420 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9749
2026-09-14 17:22:58,154 | INFO     | src.services.training | [RM-a] epoch 3/3 val F1-macro 0.9728
2026-09-14 17:22:58,305 | INFO     | src.services.campaign | [rma] RUN #18 val F1-macro 0.9749 (epoch terbaik 2)
2026-09-14 17:22:58,307 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 18/24 (perkiraan sisa 12.3 menit)
2026-09-14 17:22:58,309 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 18 run
2026-09-14 17:22:58,309 | INFO     | src.services.campaign | [rma] RUN #19 {'lr': 1e-05, 'epochs': 8, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 66332.87it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:22:59,231 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:23:15,581 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9525
2026-09-14 17:23:32,186 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9667
2026-09-14 17:23:48,602 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9683
2026-09-14 17:24:05,142 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9728
2026-09-14 17:24:21,975 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9750
2026-09-14 17:24:38,552 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9796
2026-09-14 17:24:55,101 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9745
2026-09-14 17:25:11,463 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9771
2026-09-14 17:25:11,613 | INFO     | src.services.campaign | [rma] RUN #19 val F1-macro 0.9796 (epoch terbaik 6)
2026-09-14 17:25:11,618 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 19/24 (perkiraan sisa 10.7 menit)
2026-09-14 17:25:11,621 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 19 run
2026-09-14 17:25:11,621 | INFO     | src.services.campaign | [rma] RUN #20 {'lr': 3e-05, 'epochs': 5, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57614.86it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:25:12,623 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:25:29,081 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9703
2026-09-14 17:25:45,609 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9692
2026-09-14 17:26:02,012 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9668
2026-09-14 17:26:18,409 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9707
2026-09-14 17:26:35,223 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9784
2026-09-14 17:26:35,714 | INFO     | src.services.campaign | [rma] RUN #20 val F1-macro 0.9784 (epoch terbaik 5)
2026-09-14 17:26:35,719 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 20/24 (perkiraan sisa 8.8 menit)
2026-09-14 17:26:35,722 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 20 run
2026-09-14 17:26:35,722 | INFO     | src.services.campaign | [rma] RUN #21 {'lr': 3e-05, 'epochs': 3, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56278.50it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:26:36,922 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:26:53,284 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9746
2026-09-14 17:27:09,804 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9724
2026-09-14 17:27:26,186 | INFO     | src.services.training | [RM-a] epoch 3/3 val F1-macro 0.9796
2026-09-14 17:27:26,508 | INFO     | src.services.campaign | [rma] RUN #21 val F1-macro 0.9796 (epoch terbaik 3)
2026-09-14 17:27:26,509 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 21/24 (perkiraan sisa 6.9 menit)
2026-09-14 17:27:26,512 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 21 run
2026-09-14 17:27:26,512 | INFO     | src.services.campaign | [rma] RUN #22 {'lr': 3e-05, 'epochs': 8, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56066.80it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:27:27,314 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:27:43,763 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9643
2026-09-14 17:28:00,461 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9607
2026-09-14 17:28:16,925 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9796
2026-09-14 17:28:33,512 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9680
2026-09-14 17:28:49,891 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9784
2026-09-14 17:29:06,342 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9832
2026-09-14 17:29:23,061 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9820
2026-09-14 17:29:39,550 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9820
2026-09-14 17:29:39,702 | INFO     | src.services.run_log | Juara baru untuk rma: val F1-macro 0.9832 (sebelumnya 0.9822)
2026-09-14 17:29:41,345 | INFO     | src.services.campaign | [rma] RUN #22 val F1-macro 0.9832 (epoch terbaik 6)
2026-09-14 17:29:41,346 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 22/24 (perkiraan sisa 5.2 menit)
2026-09-14 17:29:41,349 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 22 run
2026-09-14 17:29:41,349 | INFO     | src.services.campaign | [rma] RUN #23 {'lr': 5e-05, 'epochs': 5, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 55726.16it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:29:42,169 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:29:58,572 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9646
2026-09-14 17:30:15,284 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9677
2026-09-14 17:30:31,824 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9651
2026-09-14 17:30:48,285 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9698
2026-09-14 17:31:04,860 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9697
2026-09-14 17:31:05,017 | INFO     | src.services.campaign | [rma] RUN #23 val F1-macro 0.9698 (epoch terbaik 4)
2026-09-14 17:31:05,018 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 23/24 (perkiraan sisa 3.4 menit)
2026-09-14 17:31:05,021 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 23 run
2026-09-14 17:31:05,021 | INFO     | src.services.campaign | [rma] RUN #24 {'lr': 5e-05, 'epochs': 3, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56149.78it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:31:06,042 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:31:22,541 | INFO     | src.services.training | [RM-a] epoch 1/3 val F1-macro 0.9713
2026-09-14 17:31:39,119 | INFO     | src.services.training | [RM-a] epoch 2/3 val F1-macro 0.9650
2026-09-14 17:31:55,493 | INFO     | src.services.training | [RM-a] epoch 3/3 val F1-macro 0.9644
2026-09-14 17:31:55,650 | INFO     | src.services.campaign | [rma] RUN #24 val F1-macro 0.9713 (epoch terbaik 1)
2026-09-14 17:31:55,651 | INFO     | src.services.campaign | Batch rma_tahap1_grid: 24/24 (perkiraan sisa 1.7 menit)
2026-09-14 17:31:55,654 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 24 run
2026-09-14 17:31:55,654 | INFO     | src.services.campaign | [rma] RUN #25 {'lr': 5e-05, 'epochs': 8, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 56331.68it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:31:56,520 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:32:12,935 | INFO     | src.services.training | [RM-a] epoch 1/8 val F1-macro 0.9562
2026-09-14 17:32:29,608 | INFO     | src.services.training | [RM-a] epoch 2/8 val F1-macro 0.9617
2026-09-14 17:32:46,153 | INFO     | src.services.training | [RM-a] epoch 3/8 val F1-macro 0.9733
2026-09-14 17:33:02,773 | INFO     | src.services.training | [RM-a] epoch 4/8 val F1-macro 0.9381
2026-09-14 17:33:19,149 | INFO     | src.services.training | [RM-a] epoch 5/8 val F1-macro 0.9726
2026-09-14 17:33:35,613 | INFO     | src.services.training | [RM-a] epoch 6/8 val F1-macro 0.9762
2026-09-14 17:33:52,396 | INFO     | src.services.training | [RM-a] epoch 7/8 val F1-macro 0.9736
2026-09-14 17:34:08,791 | INFO     | src.services.training | [RM-a] epoch 8/8 val F1-macro 0.9760
2026-09-14 17:34:08,965 | INFO     | src.services.campaign | [rma] RUN #25 val F1-macro 0.9762 (epoch terbaik 6)
2026-09-14 17:34:09,402 | INFO     | src.services.campaign | Batch rma_tahap1_grid selesai: 24/24 berhasil dalam 41.0 menit

,run_id,lr,epochs,batch,val_f1_macro,val_f1_judi,train_time_s,is_tie_with_best
20,22,0.00003,8,32,0.983223,0.972549,132.18,True
12,14,0.00002,5,32,0.982160,0.970874,82.95,False
17,19,0.00001,8,32,0.979597,0.966601,132.17,False
19,21,0.00003,3,32,0.979597,0.966601,49.31,False
3,5,0.00001,5,16,0.978495,0.964844,107.11,True
18,20,0.00003,5,32,0.978430,0.964706,82.79,False
5,7,0.00001,8,16,0.977403,0.963107,170.86,True
1,3,0.00002,3,16,0.977266,0.962818,64.15,True
14,16,0.00002,8,32,0.977126,0.962525,131.59,False
2,4,0.00002,8,16,0.976321,0.961390,171.34,False

Baca grid sebagai permukaan, bukan daftar. Heatmap `lr x epochs` per nilai
`batch` di `outputs/tuning/figures/` memperlihatkan apakah learning rate optimal
ikut bergeser saat batch berubah. Pemenang yang duduk di tepi grid adalah sinyal
untuk melebarkan rentang, bukan untuk langsung dikunci.

Selisih di bawah 0,15 pp dihitung seri karena hanya ada satu seed; pada kondisi
seri, pilih konfigurasi yang lebih murah.

In [6]:
hasil_rma_tahap2 = runner.run_batch("rma", muat_grid("RMA_TUNING_GRID_STAGE2.csv"),
                                    batch_id="rma_tahap2_coordinate")
hasil_rma_tahap2[["run_id", "warmup_ratio", "weight_decay", "val_f1_macro",
                  "delta_vs_best_f1_macro_pp", "is_tie_with_best"]]

2026-09-14 17:34:09,416 | INFO     | src.services.campaign | Batch rma_tahap2_coordinate: 2 konfigurasi akan dijalankan
2026-09-14 17:34:09,417 | INFO     | src.services.campaign | Batch rma_tahap2_coordinate: 1/2 (perkiraan sisa 0.0 menit)
2026-09-14 17:34:09,419 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 25 run
2026-09-14 17:34:09,419 | INFO     | src.services.campaign | [rma] RUN #26 {'lr': 2e-05, 'epochs': 5, 'batch': 32, 'warmup_ratio': 0.0, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 55433.78it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:34:10,517 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:34:26,942 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9721
2026-09-14 17:34:43,597 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9659
2026-09-14 17:34:59,961 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9694
2026-09-14 17:35:16,357 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9750
2026-09-14 17:35:33,008 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9773
2026-09-14 17:35:33,418 | INFO     | src.services.campaign | [rma] RUN #26 val F1-macro 0.9773 (epoch terbaik 5)
2026-09-14 17:35:33,423 | INFO     | src.services.campaign | Batch rma_tahap2_coordinate: 2/2 (perkiraan sisa 1.4 menit)
2026-09-14 17:35:33,426 | INFO     | src.services.run_log | Riwayat runs_rma.csv dimuat: 26 run
2026-09-14 17:35:33,426 | INFO     | src.services.campaign | [rma] RUN #27 {'lr': 2e-05, 'epochs': 5, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.1, 'micro_batch': 32, 'seed': 42}

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `5`.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57381.17it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-base-p2
Key               | Status  |
------------------+---------+-
classifier.bias   | MISSING |
classifier.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

2026-09-14 17:35:34,421 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3
2026-09-14 17:35:50,859 | INFO     | src.services.training | [RM-a] epoch 1/5 val F1-macro 0.9697
2026-09-14 17:36:07,437 | INFO     | src.services.training | [RM-a] epoch 2/5 val F1-macro 0.9675
2026-09-14 17:36:23,875 | INFO     | src.services.training | [RM-a] epoch 3/5 val F1-macro 0.9782
2026-09-14 17:36:40,419 | INFO     | src.services.training | [RM-a] epoch 4/5 val F1-macro 0.9822
2026-09-14 17:36:57,171 | INFO     | src.services.training | [RM-a] epoch 5/5 val F1-macro 0.9783
2026-09-14 17:36:57,328 | INFO     | src.services.campaign | [rma] RUN #27 val F1-macro 0.9822 (epoch terbaik 4)
2026-09-14 17:36:57,923 | INFO     | src.services.campaign | Batch rma_tahap2_coordinate selesai: 2/2 berhasil dalam 2.8 menit

,run_id,warmup_ratio,weight_decay,val_f1_macro,delta_vs_best_f1_macro_pp,is_tie_with_best
0,26,0.0,0.01,0.977266,-0.5957,False
1,27,0.1,0.10,0.982160,-0.1063,True

## 4. RM-b

In [7]:
hasil_rmb = []
for berkas in ("RMB_TUNING_GRID.csv", "RMB_TUNING_GRID_STAGE1B.csv",
               "RMB_TUNING_GRID_STAGE2.csv", "RMB_TUNING_GRID_STAGE3.csv"):
    hasil_rmb.append(runner.run_batch("rmb", muat_grid(berkas),
                                      batch_id=berkas.replace(".csv", "").lower()))

pd.concat(hasil_rmb, ignore_index=True).nlargest(10, "val_f1_macro")[
    ["run_id", "head_arch", "hidden_dim", "lr", "epochs", "dropout",
     "val_f1_macro", "train_time_s", "trainable_params"]
]

2026-09-14 17:36:57,932 | INFO     | src.services.campaign | Batch rmb_tuning_grid: 4 konfigurasi akan dijalankan
2026-09-14 17:36:57,932 | INFO     | src.services.campaign | Batch rmb_tuning_grid: 1/4 (perkiraan sisa 0.0 menit)
2026-09-14 17:36:57,933 | INFO     | src.services.campaign | [rmb] RUN #1 {'head_arch': 'linear', 'hidden_dim': 256, 'epochs': 5, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:36:57,933 | INFO     | src.services.features | Ekstraksi fitur beku dengan encoder indobenchmark/indobert-base-p2

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 57670.59it/s]

2026-09-14 17:36:58,782 | INFO     | src.models.heads | Inisialisasi embedding special token: 3/3

2026-09-14 17:37:04,073 | INFO     | src.services.features |   train: (6588, 768)
2026-09-14 17:37:05,161 | INFO     | src.services.features |   val: (1402, 768)
2026-09-14 17:37:06,255 | INFO     | src.services.features |   test: (1405, 768)
2026-09-14 17:37:06,374 | INFO     | src.services.features | Fitur beku disimpan ke /workspace/indobert-with-rac/outputs/tuning/features/indobenchmark__indobert-base-p2
2026-09-14 17:37:07,140 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9125 (sebelumnya -1.0000)
2026-09-14 17:37:07,274 | INFO     | src.services.campaign | [rmb] RUN #1 val F1-macro 0.9125 (epoch terbaik 5)
2026-09-14 17:37:07,275 | INFO     | src.services.campaign | Batch rmb_tuning_grid: 2/4 (perkiraan sisa 0.5 menit)
2026-09-14 17:37:07,277 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 1 run
2026-09-14 17:37:07,278 | INFO     | src.services.campaign | [rmb] RUN #2 {'head_arch': 'mlp', 'hidden_dim': 128, 'epochs': 5, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:08,196 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9368 (sebelumnya 0.9125)
2026-09-14 17:37:08,331 | INFO     | src.services.campaign | [rmb] RUN #2 val F1-macro 0.9368 (epoch terbaik 4)
2026-09-14 17:37:08,332 | INFO     | src.services.campaign | Batch rmb_tuning_grid: 3/4 (perkiraan sisa 0.2 menit)
2026-09-14 17:37:08,334 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 2 run
2026-09-14 17:37:08,334 | INFO     | src.services.campaign | [rmb] RUN #3 {'head_arch': 'mlp', 'hidden_dim': 256, 'epochs': 5, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:09,255 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9400 (sebelumnya 0.9368)
2026-09-14 17:37:09,392 | INFO     | src.services.campaign | [rmb] RUN #3 val F1-macro 0.9400 (epoch terbaik 5)
2026-09-14 17:37:09,392 | INFO     | src.services.campaign | Batch rmb_tuning_grid: 4/4 (perkiraan sisa 0.1 menit)
2026-09-14 17:37:09,395 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 3 run
2026-09-14 17:37:09,395 | INFO     | src.services.campaign | [rmb] RUN #4 {'head_arch': 'mlp', 'hidden_dim': 512, 'epochs': 5, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:10,310 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9487 (sebelumnya 0.9400)
2026-09-14 17:37:10,450 | INFO     | src.services.campaign | [rmb] RUN #4 val F1-macro 0.9487 (epoch terbaik 5)
2026-09-14 17:37:10,635 | INFO     | src.services.campaign | Batch rmb_tuning_grid selesai: 4/4 berhasil dalam 0.2 menit
2026-09-14 17:37:10,639 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage1b: 2 konfigurasi akan dijalankan
2026-09-14 17:37:10,639 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage1b: 1/2 (perkiraan sisa 0.0 menit)
2026-09-14 17:37:10,641 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 4 run
2026-09-14 17:37:10,641 | INFO     | src.services.campaign | [rmb] RUN #5 {'head_arch': 'mlp', 'hidden_dim': 768, 'epochs': 5, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:11,578 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9511 (sebelumnya 0.9487)
2026-09-14 17:37:11,717 | INFO     | src.services.campaign | [rmb] RUN #5 val F1-macro 0.9511 (epoch terbaik 5)
2026-09-14 17:37:11,717 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage1b: 2/2 (perkiraan sisa 0.0 menit)
2026-09-14 17:37:11,720 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 5 run
2026-09-14 17:37:11,720 | INFO     | src.services.campaign | [rmb] RUN #6 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 5, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:12,640 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9543 (sebelumnya 0.9511)
2026-09-14 17:37:12,779 | INFO     | src.services.campaign | [rmb] RUN #6 val F1-macro 0.9543 (epoch terbaik 4)
2026-09-14 17:37:12,958 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage1b selesai: 2/2 berhasil dalam 0.0 menit
2026-09-14 17:37:12,962 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 15 konfigurasi akan dijalankan
2026-09-14 17:37:12,962 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 1/15 (perkiraan sisa 0.0 menit)
2026-09-14 17:37:12,965 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 6 run
2026-09-14 17:37:12,965 | INFO     | src.services.campaign | [rmb] RUN #7 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 5, 'lr': 0.0001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:13,889 | INFO     | src.services.campaign | [rmb] RUN #7 val F1-macro 0.9413 (epoch terbaik 5)
2026-09-14 17:37:13,889 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 2/15 (perkiraan sisa 0.2 menit)
2026-09-14 17:37:13,892 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 7 run
2026-09-14 17:37:13,892 | INFO     | src.services.campaign | [rmb] RUN #8 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.0001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:15,590 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9561 (sebelumnya 0.9543)
2026-09-14 17:37:15,729 | INFO     | src.services.campaign | [rmb] RUN #8 val F1-macro 0.9561 (epoch terbaik 10)
2026-09-14 17:37:15,729 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 3/15 (perkiraan sisa 0.3 menit)
2026-09-14 17:37:15,732 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 8 run
2026-09-14 17:37:15,733 | INFO     | src.services.campaign | [rmb] RUN #9 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 20, 'lr': 0.0001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:18,926 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9612 (sebelumnya 0.9561)
2026-09-14 17:37:19,065 | INFO     | src.services.campaign | [rmb] RUN #9 val F1-macro 0.9612 (epoch terbaik 18)
2026-09-14 17:37:19,066 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 4/15 (perkiraan sisa 0.4 menit)
2026-09-14 17:37:19,069 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 9 run
2026-09-14 17:37:19,069 | INFO     | src.services.campaign | [rmb] RUN #10 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 30, 'lr': 0.0001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:23,804 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9628 (sebelumnya 0.9612)
2026-09-14 17:37:23,943 | INFO     | src.services.campaign | [rmb] RUN #10 val F1-macro 0.9628 (epoch terbaik 23)
2026-09-14 17:37:23,944 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 5/15 (perkiraan sisa 0.5 menit)
2026-09-14 17:37:23,948 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 10 run
2026-09-14 17:37:23,949 | INFO     | src.services.campaign | [rmb] RUN #11 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:25,656 | INFO     | src.services.campaign | [rmb] RUN #11 val F1-macro 0.9618 (epoch terbaik 9)
2026-09-14 17:37:25,656 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 6/15 (perkiraan sisa 0.4 menit)
2026-09-14 17:37:25,659 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 11 run
2026-09-14 17:37:25,659 | INFO     | src.services.campaign | [rmb] RUN #12 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 20, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:28,860 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9629 (sebelumnya 0.9628)
2026-09-14 17:37:28,999 | INFO     | src.services.campaign | [rmb] RUN #12 val F1-macro 0.9629 (epoch terbaik 15)
2026-09-14 17:37:28,999 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 7/15 (perkiraan sisa 0.4 menit)
2026-09-14 17:37:29,002 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 12 run
2026-09-14 17:37:29,002 | INFO     | src.services.campaign | [rmb] RUN #13 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 30, 'lr': 0.0002, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:33,879 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9637 (sebelumnya 0.9629)
2026-09-14 17:37:34,019 | INFO     | src.services.campaign | [rmb] RUN #13 val F1-macro 0.9637 (epoch terbaik 22)
2026-09-14 17:37:34,019 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 8/15 (perkiraan sisa 0.4 menit)
2026-09-14 17:37:34,022 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 13 run
2026-09-14 17:37:34,022 | INFO     | src.services.campaign | [rmb] RUN #14 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 5, 'lr': 0.0005, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:34,953 | INFO     | src.services.campaign | [rmb] RUN #14 val F1-macro 0.9579 (epoch terbaik 4)
2026-09-14 17:37:34,953 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 9/15 (perkiraan sisa 0.3 menit)
2026-09-14 17:37:34,956 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 14 run
2026-09-14 17:37:34,956 | INFO     | src.services.campaign | [rmb] RUN #15 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.0005, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:36,613 | INFO     | src.services.campaign | [rmb] RUN #15 val F1-macro 0.9613 (epoch terbaik 6)
2026-09-14 17:37:36,613 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 10/15 (perkiraan sisa 0.3 menit)
2026-09-14 17:37:36,616 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 15 run
2026-09-14 17:37:36,616 | INFO     | src.services.campaign | [rmb] RUN #16 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 20, 'lr': 0.0005, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:39,824 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9640 (sebelumnya 0.9637)
2026-09-14 17:37:39,963 | INFO     | src.services.campaign | [rmb] RUN #16 val F1-macro 0.9640 (epoch terbaik 12)
2026-09-14 17:37:39,964 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 11/15 (perkiraan sisa 0.2 menit)
2026-09-14 17:37:39,966 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 16 run
2026-09-14 17:37:39,966 | INFO     | src.services.campaign | [rmb] RUN #17 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 30, 'lr': 0.0005, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:44,694 | INFO     | src.services.campaign | [rmb] RUN #17 val F1-macro 0.9640 (epoch terbaik 12)
2026-09-14 17:37:44,694 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 12/15 (perkiraan sisa 0.2 menit)
2026-09-14 17:37:44,697 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 17 run
2026-09-14 17:37:44,697 | INFO     | src.services.campaign | [rmb] RUN #18 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 5, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:45,677 | INFO     | src.services.campaign | [rmb] RUN #18 val F1-macro 0.9595 (epoch terbaik 5)
2026-09-14 17:37:45,678 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 13/15 (perkiraan sisa 0.1 menit)
2026-09-14 17:37:45,680 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 18 run
2026-09-14 17:37:45,681 | INFO     | src.services.campaign | [rmb] RUN #19 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:47,374 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9650 (sebelumnya 0.9640)
2026-09-14 17:37:47,514 | INFO     | src.services.campaign | [rmb] RUN #19 val F1-macro 0.9650 (epoch terbaik 6)
2026-09-14 17:37:47,515 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 14/15 (perkiraan sisa 0.1 menit)
2026-09-14 17:37:47,518 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 19 run
2026-09-14 17:37:47,518 | INFO     | src.services.campaign | [rmb] RUN #20 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 20, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:50,741 | INFO     | src.services.campaign | [rmb] RUN #20 val F1-macro 0.9650 (epoch terbaik 6)
2026-09-14 17:37:50,742 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2: 15/15 (perkiraan sisa 0.0 menit)
2026-09-14 17:37:50,745 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 20 run
2026-09-14 17:37:50,745 | INFO     | src.services.campaign | [rmb] RUN #21 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 30, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:55,502 | INFO     | src.services.campaign | [rmb] RUN #21 val F1-macro 0.9650 (epoch terbaik 6)
2026-09-14 17:37:56,069 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage2 selesai: 15/15 berhasil dalam 0.7 menit
2026-09-14 17:37:56,074 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3: 6 konfigurasi akan dijalankan
2026-09-14 17:37:56,074 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3: 1/6 (perkiraan sisa 0.0 menit)
2026-09-14 17:37:56,076 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 21 run
2026-09-14 17:37:56,076 | INFO     | src.services.campaign | [rmb] RUN #22 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.0, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:57,717 | INFO     | src.services.campaign | [rmb] RUN #22 val F1-macro 0.9606 (epoch terbaik 10)
2026-09-14 17:37:57,718 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3: 2/6 (perkiraan sisa 0.1 menit)
2026-09-14 17:37:57,721 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 22 run
2026-09-14 17:37:57,721 | INFO     | src.services.campaign | [rmb] RUN #23 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.3, 'weight_decay': 0.01, 'batch': 32, 'seed': 42}
2026-09-14 17:37:59,424 | INFO     | src.services.campaign | [rmb] RUN #23 val F1-macro 0.9638 (epoch terbaik 6)
2026-09-14 17:37:59,424 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3: 3/6 (perkiraan sisa 0.1 menit)
2026-09-14 17:37:59,427 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 23 run
2026-09-14 17:37:59,428 | INFO     | src.services.campaign | [rmb] RUN #24 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.0, 'batch': 32, 'seed': 42}
2026-09-14 17:38:01,088 | INFO     | src.services.run_log | Juara baru untuk rmb: val F1-macro 0.9653 (sebelumnya 0.9650)
2026-09-14 17:38:01,228 | INFO     | src.services.campaign | [rmb] RUN #24 val F1-macro 0.9653 (epoch terbaik 6)
2026-09-14 17:38:01,229 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3: 4/6 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:01,231 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 24 run
2026-09-14 17:38:01,231 | INFO     | src.services.campaign | [rmb] RUN #25 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.1, 'batch': 32, 'seed': 42}
2026-09-14 17:38:03,032 | INFO     | src.services.campaign | [rmb] RUN #25 val F1-macro 0.9603 (epoch terbaik 10)
2026-09-14 17:38:03,033 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3: 5/6 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:03,035 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 25 run
2026-09-14 17:38:03,036 | INFO     | src.services.campaign | [rmb] RUN #26 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 16, 'seed': 42}
2026-09-14 17:38:06,021 | INFO     | src.services.campaign | [rmb] RUN #26 val F1-macro 0.9571 (epoch terbaik 7)
2026-09-14 17:38:06,022 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3: 6/6 (perkiraan sisa 0.0 menit)
2026-09-14 17:38:06,025 | INFO     | src.services.run_log | Riwayat runs_rmb.csv dimuat: 26 run
2026-09-14 17:38:06,025 | INFO     | src.services.campaign | [rmb] RUN #27 {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.01, 'batch': 64, 'seed': 42}
2026-09-14 17:38:08,044 | INFO     | src.services.campaign | [rmb] RUN #27 val F1-macro 0.9636 (epoch terbaik 9)
2026-09-14 17:38:08,743 | INFO     | src.services.campaign | Batch rmb_tuning_grid_stage3 selesai: 6/6 berhasil dalam 0.2 menit

,run_id,head_arch,hidden_dim,lr,epochs,dropout,val_f1_macro,train_time_s,trainable_params
23,24,mlp,1024,0.0010,10,0.1,0.965301,9.03,789506
18,19,mlp,1024,0.0010,10,0.1,0.964980,9.06,789506
19,20,mlp,1024,0.0010,20,0.1,0.964980,10.58,789506
20,21,mlp,1024,0.0010,30,0.1,0.964980,12.12,789506
15,16,mlp,1024,0.0005,20,0.1,0.964049,10.56,789506
16,17,mlp,1024,0.0005,30,0.1,0.964049,12.09,789506
22,23,mlp,1024,0.0010,10,0.3,0.963828,9.06,789506
12,13,mlp,1024,0.0002,30,0.1,0.963716,12.06,789506
26,27,mlp,1024,0.0010,10,0.1,0.963603,8.49,789506
11,12,mlp,1024,0.0002,20,0.1,0.962908,10.56,789506

## 5. RM-c

RM-c mewarisi head RM-b terbaik, jadi kampanye ini harus dijalankan SETELAH
RM-b selesai. Karena tidak ada training sama sekali, ratusan kombinasi
`alpha x k` selesai dalam hitungan detik.

In [8]:
hasil_rmc = []
for berkas in ("RMC_TUNING_GRID.csv", "RMC_TUNING_GRID_STAGE2.csv"):
    hasil_rmc.append(runner.run_batch("rmc", muat_grid(berkas),
                                      batch_id=berkas.replace(".csv", "").lower()))

pd.concat(hasil_rmc, ignore_index=True).nlargest(10, "val_f1_macro")[
    ["run_id", "alpha", "k", "weighting", "val_f1_macro", "val_f1_judi", "eval_time_s"]
]

2026-09-14 17:38:08,767 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 66 konfigurasi akan dijalankan
2026-09-14 17:38:08,767 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 1/66 (perkiraan sisa 0.0 menit)
2026-09-14 17:38:08,768 | INFO     | src.services.campaign | [rmc] RUN #1 {'alpha': 0.0, 'k': 1, 'weighting': 'similarity'}
2026-09-14 17:38:08,788 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:08,906 | INFO     | src.services.run_log | Juara baru untuk rmc: val F1-macro 0.9653 (sebelumnya -1.0000)
2026-09-14 17:38:08,908 | INFO     | src.services.campaign | [rmc] RUN #1 val F1-macro 0.9653
2026-09-14 17:38:08,910 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 2/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:08,918 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 1 run
2026-09-14 17:38:08,919 | INFO     | src.services.campaign | [rmc] RUN #2 {'alpha': 0.0, 'k': 3, 'weighting': 'similarity'}
2026-09-14 17:38:08,940 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:09,045 | INFO     | src.services.campaign | [rmc] RUN #2 val F1-macro 0.9653
2026-09-14 17:38:09,047 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 3/66 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:09,055 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 2 run
2026-09-14 17:38:09,057 | INFO     | src.services.campaign | [rmc] RUN #3 {'alpha': 0.0, 'k': 5, 'weighting': 'similarity'}
2026-09-14 17:38:09,078 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:09,300 | INFO     | src.services.campaign | [rmc] RUN #3 val F1-macro 0.9653
2026-09-14 17:38:09,302 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 4/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:09,315 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 3 run
2026-09-14 17:38:09,316 | INFO     | src.services.campaign | [rmc] RUN #4 {'alpha': 0.0, 'k': 10, 'weighting': 'similarity'}
2026-09-14 17:38:09,339 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:09,452 | INFO     | src.services.campaign | [rmc] RUN #4 val F1-macro 0.9653
2026-09-14 17:38:09,454 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 5/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:09,462 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 4 run
2026-09-14 17:38:09,463 | INFO     | src.services.campaign | [rmc] RUN #5 {'alpha': 0.0, 'k': 20, 'weighting': 'similarity'}
2026-09-14 17:38:09,484 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:09,702 | INFO     | src.services.campaign | [rmc] RUN #5 val F1-macro 0.9653
2026-09-14 17:38:09,703 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 6/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:09,707 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 5 run
2026-09-14 17:38:09,708 | INFO     | src.services.campaign | [rmc] RUN #6 {'alpha': 0.0, 'k': 50, 'weighting': 'similarity'}
2026-09-14 17:38:09,733 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:09,792 | INFO     | src.services.campaign | [rmc] RUN #6 val F1-macro 0.9653
2026-09-14 17:38:09,793 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 7/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:09,795 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 6 run
2026-09-14 17:38:09,796 | INFO     | src.services.campaign | [rmc] RUN #7 {'alpha': 0.1, 'k': 1, 'weighting': 'similarity'}
2026-09-14 17:38:09,865 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:10,075 | INFO     | src.services.campaign | [rmc] RUN #7 val F1-macro 0.9653
2026-09-14 17:38:10,079 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 8/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:10,093 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 7 run
2026-09-14 17:38:10,095 | INFO     | src.services.campaign | [rmc] RUN #8 {'alpha': 0.1, 'k': 3, 'weighting': 'similarity'}
2026-09-14 17:38:10,171 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:10,351 | INFO     | src.services.campaign | [rmc] RUN #8 val F1-macro 0.9628
2026-09-14 17:38:10,354 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 9/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:10,364 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 8 run
2026-09-14 17:38:10,365 | INFO     | src.services.campaign | [rmc] RUN #9 {'alpha': 0.1, 'k': 5, 'weighting': 'similarity'}
2026-09-14 17:38:10,405 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:10,684 | INFO     | src.services.campaign | [rmc] RUN #9 val F1-macro 0.9652
2026-09-14 17:38:10,686 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 10/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:10,698 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 9 run
2026-09-14 17:38:10,700 | INFO     | src.services.campaign | [rmc] RUN #10 {'alpha': 0.1, 'k': 10, 'weighting': 'similarity'}
2026-09-14 17:38:10,771 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:10,881 | INFO     | src.services.campaign | [rmc] RUN #10 val F1-macro 0.9652
2026-09-14 17:38:10,883 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 11/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:10,895 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 10 run
2026-09-14 17:38:10,897 | INFO     | src.services.campaign | [rmc] RUN #11 {'alpha': 0.1, 'k': 20, 'weighting': 'similarity'}
2026-09-14 17:38:10,973 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:11,095 | INFO     | src.services.campaign | [rmc] RUN #11 val F1-macro 0.9652
2026-09-14 17:38:11,145 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 12/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:11,159 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 11 run
2026-09-14 17:38:11,161 | INFO     | src.services.campaign | [rmc] RUN #12 {'alpha': 0.1, 'k': 50, 'weighting': 'similarity'}
2026-09-14 17:38:11,188 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:11,424 | INFO     | src.services.campaign | [rmc] RUN #12 val F1-macro 0.9639
2026-09-14 17:38:11,445 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 13/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:11,454 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 12 run
2026-09-14 17:38:11,455 | INFO     | src.services.campaign | [rmc] RUN #13 {'alpha': 0.2, 'k': 1, 'weighting': 'similarity'}
2026-09-14 17:38:11,488 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:11,748 | INFO     | src.services.run_log | Juara baru untuk rmc: val F1-macro 0.9700 (sebelumnya 0.9653)
2026-09-14 17:38:11,751 | INFO     | src.services.campaign | [rmc] RUN #13 val F1-macro 0.9700
2026-09-14 17:38:11,754 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 14/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:11,767 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 13 run
2026-09-14 17:38:11,767 | INFO     | src.services.campaign | [rmc] RUN #14 {'alpha': 0.2, 'k': 3, 'weighting': 'similarity'}
2026-09-14 17:38:11,785 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:11,963 | INFO     | src.services.campaign | [rmc] RUN #14 val F1-macro 0.9687
2026-09-14 17:38:11,965 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 15/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:11,977 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 14 run
2026-09-14 17:38:11,979 | INFO     | src.services.campaign | [rmc] RUN #15 {'alpha': 0.2, 'k': 5, 'weighting': 'similarity'}
2026-09-14 17:38:12,004 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:12,182 | INFO     | src.services.campaign | [rmc] RUN #15 val F1-macro 0.9699
2026-09-14 17:38:12,184 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 16/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:12,192 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 15 run
2026-09-14 17:38:12,193 | INFO     | src.services.campaign | [rmc] RUN #16 {'alpha': 0.2, 'k': 10, 'weighting': 'similarity'}
2026-09-14 17:38:12,256 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:12,571 | INFO     | src.services.campaign | [rmc] RUN #16 val F1-macro 0.9662
2026-09-14 17:38:12,573 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 17/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:12,588 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 16 run
2026-09-14 17:38:12,589 | INFO     | src.services.campaign | [rmc] RUN #17 {'alpha': 0.2, 'k': 20, 'weighting': 'similarity'}
2026-09-14 17:38:12,674 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:12,791 | INFO     | src.services.campaign | [rmc] RUN #17 val F1-macro 0.9662
2026-09-14 17:38:12,793 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 18/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:12,798 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 17 run
2026-09-14 17:38:12,844 | INFO     | src.services.campaign | [rmc] RUN #18 {'alpha': 0.2, 'k': 50, 'weighting': 'similarity'}
2026-09-14 17:38:12,878 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:13,100 | INFO     | src.services.campaign | [rmc] RUN #18 val F1-macro 0.9650
2026-09-14 17:38:13,145 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 19/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:13,155 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 18 run
2026-09-14 17:38:13,156 | INFO     | src.services.campaign | [rmc] RUN #19 {'alpha': 0.3, 'k': 1, 'weighting': 'similarity'}
2026-09-14 17:38:13,178 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:13,461 | INFO     | src.services.campaign | [rmc] RUN #19 val F1-macro 0.9675
2026-09-14 17:38:13,463 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 20/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:13,475 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 19 run
2026-09-14 17:38:13,477 | INFO     | src.services.campaign | [rmc] RUN #20 {'alpha': 0.3, 'k': 3, 'weighting': 'similarity'}
2026-09-14 17:38:13,504 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:13,851 | INFO     | src.services.campaign | [rmc] RUN #20 val F1-macro 0.9673
2026-09-14 17:38:13,853 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 21/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:13,867 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 20 run
2026-09-14 17:38:13,869 | INFO     | src.services.campaign | [rmc] RUN #21 {'alpha': 0.3, 'k': 5, 'weighting': 'similarity'}
2026-09-14 17:38:13,909 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:14,052 | INFO     | src.services.campaign | [rmc] RUN #21 val F1-macro 0.9673
2026-09-14 17:38:14,054 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 22/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:14,063 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 21 run
2026-09-14 17:38:14,064 | INFO     | src.services.campaign | [rmc] RUN #22 {'alpha': 0.3, 'k': 10, 'weighting': 'similarity'}
2026-09-14 17:38:14,085 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:14,191 | INFO     | src.services.campaign | [rmc] RUN #22 val F1-macro 0.9661
2026-09-14 17:38:14,192 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 23/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:14,252 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 22 run
2026-09-14 17:38:14,253 | INFO     | src.services.campaign | [rmc] RUN #23 {'alpha': 0.3, 'k': 20, 'weighting': 'similarity'}
2026-09-14 17:38:14,285 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:14,398 | INFO     | src.services.campaign | [rmc] RUN #23 val F1-macro 0.9673
2026-09-14 17:38:14,398 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 24/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:14,447 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 23 run
2026-09-14 17:38:14,448 | INFO     | src.services.campaign | [rmc] RUN #24 {'alpha': 0.3, 'k': 50, 'weighting': 'similarity'}
2026-09-14 17:38:14,491 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:14,594 | INFO     | src.services.campaign | [rmc] RUN #24 val F1-macro 0.9661
2026-09-14 17:38:14,595 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 25/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:14,653 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 24 run
2026-09-14 17:38:14,654 | INFO     | src.services.campaign | [rmc] RUN #25 {'alpha': 0.4, 'k': 1, 'weighting': 'similarity'}
2026-09-14 17:38:14,679 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:14,814 | INFO     | src.services.campaign | [rmc] RUN #25 val F1-macro 0.9687
2026-09-14 17:38:14,815 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 26/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:14,855 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 25 run
2026-09-14 17:38:14,856 | INFO     | src.services.campaign | [rmc] RUN #26 {'alpha': 0.4, 'k': 3, 'weighting': 'similarity'}
2026-09-14 17:38:14,888 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:15,087 | INFO     | src.services.campaign | [rmc] RUN #26 val F1-macro 0.9686
2026-09-14 17:38:15,090 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 27/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:15,152 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 26 run
2026-09-14 17:38:15,153 | INFO     | src.services.campaign | [rmc] RUN #27 {'alpha': 0.4, 'k': 5, 'weighting': 'similarity'}
2026-09-14 17:38:15,185 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:15,367 | INFO     | src.services.campaign | [rmc] RUN #27 val F1-macro 0.9686
2026-09-14 17:38:15,369 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 28/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:15,380 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 27 run
2026-09-14 17:38:15,381 | INFO     | src.services.campaign | [rmc] RUN #28 {'alpha': 0.4, 'k': 10, 'weighting': 'similarity'}
2026-09-14 17:38:15,400 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:15,749 | INFO     | src.services.campaign | [rmc] RUN #28 val F1-macro 0.9685
2026-09-14 17:38:15,752 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 29/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:15,766 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 28 run
2026-09-14 17:38:15,768 | INFO     | src.services.campaign | [rmc] RUN #29 {'alpha': 0.4, 'k': 20, 'weighting': 'similarity'}
2026-09-14 17:38:15,791 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:15,987 | INFO     | src.services.campaign | [rmc] RUN #29 val F1-macro 0.9672
2026-09-14 17:38:15,990 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 30/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:16,047 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 29 run
2026-09-14 17:38:16,049 | INFO     | src.services.campaign | [rmc] RUN #30 {'alpha': 0.4, 'k': 50, 'weighting': 'similarity'}
2026-09-14 17:38:16,080 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:16,267 | INFO     | src.services.campaign | [rmc] RUN #30 val F1-macro 0.9672
2026-09-14 17:38:16,269 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 31/66 (perkiraan sisa 0.2 menit)
2026-09-14 17:38:16,284 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 30 run
2026-09-14 17:38:16,285 | INFO     | src.services.campaign | [rmc] RUN #31 {'alpha': 0.5, 'k': 1, 'weighting': 'similarity'}
2026-09-14 17:38:16,314 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:16,671 | INFO     | src.services.campaign | [rmc] RUN #31 val F1-macro 0.9382
2026-09-14 17:38:16,674 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 32/66 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:16,684 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 31 run
2026-09-14 17:38:16,686 | INFO     | src.services.campaign | [rmc] RUN #32 {'alpha': 0.5, 'k': 3, 'weighting': 'similarity'}
2026-09-14 17:38:16,767 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:16,882 | INFO     | src.services.campaign | [rmc] RUN #32 val F1-macro 0.9658
2026-09-14 17:38:16,884 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 33/66 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:16,898 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 32 run
2026-09-14 17:38:16,899 | INFO     | src.services.campaign | [rmc] RUN #33 {'alpha': 0.5, 'k': 5, 'weighting': 'similarity'}
2026-09-14 17:38:16,980 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:17,058 | INFO     | src.services.campaign | [rmc] RUN #33 val F1-macro 0.9684
2026-09-14 17:38:17,059 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 34/66 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:17,061 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 33 run
2026-09-14 17:38:17,061 | INFO     | src.services.campaign | [rmc] RUN #34 {'alpha': 0.5, 'k': 10, 'weighting': 'similarity'}
2026-09-14 17:38:17,077 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:17,170 | INFO     | src.services.campaign | [rmc] RUN #34 val F1-macro 0.9658
2026-09-14 17:38:17,171 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 35/66 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:17,179 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 34 run
2026-09-14 17:38:17,180 | INFO     | src.services.campaign | [rmc] RUN #35 {'alpha': 0.5, 'k': 20, 'weighting': 'similarity'}
2026-09-14 17:38:17,201 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:17,552 | INFO     | src.services.campaign | [rmc] RUN #35 val F1-macro 0.9671
2026-09-14 17:38:17,554 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 36/66 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:17,564 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 35 run
2026-09-14 17:38:17,565 | INFO     | src.services.campaign | [rmc] RUN #36 {'alpha': 0.5, 'k': 50, 'weighting': 'similarity'}
2026-09-14 17:38:17,597 | INFO     | src.services.rac | Indeks FAISS dibangun: 6588 vektor berdimensi 768
2026-09-14 17:38:17,690 | INFO     | src.services.campaign | [rmc] RUN #36 val F1-macro 0.9633
2026-09-14 17:38:17,691 | INFO     | src.services.campaign | Batch rmc_tuning_grid: 37/66 (perkiraan sisa 0.1 menit)
2026-09-14 17:38:17,695 | INFO     | src.services.run_log | Riwayat runs_rmc.csv dimuat: 36 run
2026-09-14 17:38:17,695 | INFO     | src.services.campaign | [rmc] RUN #37 {'alpha': 0.6, 'k': 1, 'weighting': 'similarity'}

    run_id  alpha   k   weighting  val_f1_macro  val_f1_judi  eval_time_s
12      13    0.2   1  similarity      0.969995     0.950884         0.18
14      15    0.2   5  similarity      0.969903     0.950690         0.17
66      67    0.2   5     uniform      0.969903     0.950690         0.05
24      25    0.4   1  similarity      0.968747     0.948819         0.09
13      14    0.2   3  similarity      0.968651     0.948617         0.10
25      26    0.4   3  similarity      0.968554     0.948413         0.18
26      27    0.4   5  similarity      0.968554     0.948413         0.11
27      28    0.4  10  similarity      0.968456     0.948207         0.27
32      33    0.5   5  similarity      0.968358     0.948000         0.07
18      19    0.3   1  similarity      0.967496     0.946746         0.20

## 6. Juara tiap skenario

In [9]:
import json

best = json.loads((OUT_DIR / "best.json").read_text(encoding="utf-8"))
for skenario, entri in best.items():
    print(f"{skenario}: run #{entri['run_id']} | val F1-macro {entri['val_f1_macro']:.4f}")
    print(f"     {entri['config']}\n")

rma: run #22 | val F1-macro 0.9832
     {'lr': 3e-05, 'epochs': 8, 'batch': 32, 'warmup_ratio': 0.1, 'weight_decay': 0.01, 'micro_batch': 32, 'seed': 42}

rmb: run #24 | val F1-macro 0.9653
     {'head_arch': 'mlp', 'hidden_dim': 1024, 'epochs': 10, 'lr': 0.001, 'dropout': 0.1, 'weight_decay': 0.0, 'batch': 32, 'seed': 42}

rmc: run #13 | val F1-macro 0.9700
     {'alpha': 0.2, 'k': 1, 'weighting': 'similarity'}

In [10]:
summary = json.loads((OUT_DIR / "tuning_summary.json").read_text(encoding="utf-8"))
print(json.dumps(summary, indent=2, ensure_ascii=False))

{
  "generated_at": "2026-09-14 17:38:27",
  "scenarios": {
    "rma": {
      "n_runs": 27,
      "first_run_at": "2026-09-14 16:53:07",
      "last_run_at": "2026-09-14 17:36:57",
      "n_batches": 2,
      "best_run_id": 22,
      "best_val_f1_macro": 0.9832230712686121
    },
    "rmb": {
      "n_runs": 27,
      "first_run_at": "2026-09-14 17:37:06",
      "last_run_at": "2026-09-14 17:38:07",
      "n_batches": 4,
      "best_run_id": 24,
      "best_val_f1_macro": 0.9653006725992406
    },
    "rmc": {
      "n_runs": 67,
      "first_run_at": "2026-09-14 17:38:08",
      "last_run_at": "2026-09-14 17:38:27",
      "n_batches": 2,
      "best_run_id": 13,
      "best_val_f1_macro": 0.9699954201283221
    }
  }
}

## Ringkasan

Seluruh angka di atas berasal dari split validation. Split test masih tertutup
dan baru dibuka satu kali di `05_final_benchmark.ipynb`.

Kalau ingin menambah konfigurasi setelah membaca hasil, panggil `runner.run`
atau `runner.run_batch` lagi: riwayat menumpuk dan penomoran run berlanjut.